syntax = "proto3";

package media.v1;

import "google/protobuf/timestamp.proto";
service MediaService {
  rpc UploadImage (UploadImageRequest) returns (UploadImageResponse);
  rpc GetImage (GetImageRequest) returns (GetImageResponse);
}

message UploadImageRequest {
  string file_name = 1;
  Folder folder = 2;
  string content_type = 3;
  bytes data = 4;
  optional int32 resize_width = 5;
  optional int32 resize_height = 6;
}

message UploadImageResponse {
  string key = 1;
  google.protobuf.Timestamp updated_at = 2;
}

message GetImageRequest {
  string key = 1;
}

message GetImageResponse {
  bytes data = 1;
  string content_type = 2;
}

enum Folder {
    AVATAR = 0;
    THUMBNAIL = 1;
}