syntax = "proto3";

package system.chats.v1;

import "google/protobuf/timestamp.proto";

import "common.proto";

service SystemChatsService {
  rpc GetUserMessages (GetUserMessagesRequest) returns (GetUserMessagesResponse);
}

message GetUserMessagesRequest {
  string user_id = 1;
  string public_key = 2; 
  common.v1.FieldMask select_mask = 3;
}

message GetUserMessagesResponse {
  string chat_id = 1;
  string encrypted_chat_key = 2; 
  repeated SystemMessage messages = 3;
}
message SystemMessage {
  string id = 1;
  string chat_id = 2;
  string sender_id = 3;
  string content = 4;
  string auth_tag = 5;
  string initial_vector = 6;
  bool is_edited = 7;
  bool is_deleted = 8;
  google.protobuf.Timestamp created_at = 9;
  google.protobuf.Timestamp updated_at = 10;
}