syntax = "proto3";

package video.v1;

import "google/protobuf/timestamp.proto";
import "common.proto";

service VideoService {
    rpc ConfirmVideoUpload (ConfirmVideoUploadRequest) returns (ConfirmVideoUploadResponse);
    
    rpc GetAllVideosOwner (GetAllVideosOwnerRequest) returns (GetAllVideosOwnerResponse);
    rpc PublicVideoBySlug (PublicVideoBySlugRequest) returns (PublicVideoBySlugResponce);
    rpc SettingVideoBySlug (SettingVideoBySlugRequest) returns (SettingVideoBySlugResponce);
    rpc UpdateSettingsVideo (UpdateSettingsVideoRequest) returns (UpdateSettingsVideoResponse);
}

message ConfirmVideoUploadRequest {
  string video_id = 1; 
  string file_key = 2; 
  string content_type = 3; 
  string owner_id = 4;
}

message ConfirmVideoUploadResponse {
  bool success = 1;
}

message GetAllVideosOwnerRequest {
  string owner_id = 1;
  common.v1.FieldMask select_mask = 2;
}

message GetAllVideosOwnerResponse {
  repeated Video videos = 1;
}

message PublicVideoBySlugRequest {
  string slug = 1;
}

message PublicVideoBySlugResponce {
  Video video = 1;
}

message SettingVideoBySlugRequest {
  string slug = 1;
  string owner_id= 2; 
}

message  SettingVideoBySlugResponce{
  Video video =1;
}

message UpdateSettingsVideoRequest {
  string slug = 1;
  string owner_id = 2;
  Video video = 3;
  FieldMask update_mask = 4;
  repeated string category_ids = 5;
}

message UpdateSettingsVideoResponse {
  Video video = 1;
}

message FieldMask {
  repeated string paths = 1;
}

message CheckAvailabilityCategoryRequest {
  
}
message Video {
	string id = 1;
	string owner_id = 2;
  string title = 3;
	optional string description = 4;
  Access access = 5;
  Status status= 6;
  string slug = 7;
  optional string thumbnail_url = 8;
  optional int32 duration_seconds = 9;
  optional string path = 10;
  google.protobuf.Timestamp updated_at = 11;
	google.protobuf.Timestamp created_at = 12;
  repeated VideoCategory categories = 13;
}

message VideoCategory {
  string id = 1;
}

enum Access {
  PUBLIC = 0;
  PRIVATE = 1;
  BYLINK = 2;
}

enum Status {
  PENDING = 0;
  PROCESSING = 1;
  READY = 2;
  FAILED = 3;
}
